apiVersion: apps/v1
kind: Deployment
metadata:
  name: aroma-deoghar
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aroma-deoghar
  template:
    metadata:
      labels:
        app: aroma-deoghar
    spec:
      containers:
        - name: storefront
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

          resources:
{{ toYaml .Values.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
