apiVersion: v1
kind: Service
metadata:
  name: aroma-deoghar
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: aroma-deoghar

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80

  type: {{ .Values.service.type }}
